### ISSUE TITLE
CIDRs are ignored in Multi-services per one endpoint scenario

### ISSUE THREAD

**Issue by electrocucaracha** [networkservicemesh/networkservicemesh#2186]
## Expected Behavior
Endpoint's NICs should belong to different networks.

## Current Behavior

I'm working on the NSM implementation for the [GW Tester app](https://wmnsk.com/posts/20200116_gw-tester/). I have [done this before](https://github.com/electrocucaracha/gw-tester/) for Multus and DANM and sadly the [services of this app can't be separated](https://github.com/wmnsk/go-gtp/issues/70#issuecomment-688414207) so I decided to create a sidecar which offer multiple services.

```go
package main

import (
	"context"

	"github.com/networkservicemesh/networkservicemesh/utils"

	"github.com/networkservicemesh/networkservicemesh/pkg/tools"
	"github.com/networkservicemesh/networkservicemesh/sdk/common"
	"github.com/networkservicemesh/networkservicemesh/sdk/endpoint"
	"github.com/sirupsen/logrus"
)

const (
	S5uAdvertiseNseLabelsEnv utils.EnvVar = "S5U_ADVERTISE_NSE_LABELS"
	S5uIPAddressEnv          utils.EnvVar = "S5U_IP_ADDRESS"
	S5cAdvertiseNseLabelsEnv utils.EnvVar = "S5C_ADVERTISE_NSE_LABELS"
	S5cIPAddressEnv          utils.EnvVar = "S5C_IP_ADDRESS"
	SgiAdvertiseNseLabelsEnv utils.EnvVar = "SGI_ADVERTISE_NSE_LABELS"
	SgiIPAddressEnv          utils.EnvVar = "SGI_IP_ADDRESS"
)

// SingleEndpoint keeps the state of a single endpoint instance
type SingleEndpoint struct {
	Cleanup func()
}

func main() {
	logrus.Info("Starting nse...")
	utils.PrintAllEnv(logrus.StandardLogger())
	// Capture signals to cleanup before exiting
	c := tools.NewOSSignalChannel()

	configs := []struct {
		AdvertiseNseLabels string
		IPAddress          string
	}{
		{
			AdvertiseNseLabels: S5uAdvertiseNseLabelsEnv.GetStringOrDefault("link=s5u"),
			IPAddress:          S5uIPAddressEnv.GetStringOrDefault("172.25.0.0/24"),
		},
		{
			AdvertiseNseLabels: S5cAdvertiseNseLabelsEnv.GetStringOrDefault("link=s5c"),
			IPAddress:          S5cIPAddressEnv.GetStringOrDefault("172.25.1.0/24"),
		},
		{
			AdvertiseNseLabels: SgiAdvertiseNseLabelsEnv.GetStringOrDefault("link=sgi"),
			IPAddress:          SgiIPAddressEnv.GetStringOrDefault("10.0.1.0/24"),
		},
	}

	endpoints := []*SingleEndpoint{}
	for _, config := range configs {
		configuration := common.FromEnv()
		configuration.AdvertiseNseLabels = config.AdvertiseNseLabels
		configuration.IPAddress = config.IPAddress

		composite := endpoint.NewCompositeEndpoint(
			endpoint.NewMonitorEndpoint(configuration),
			endpoint.NewConnectionEndpoint(configuration),
			endpoint.NewIpamEndpoint(configuration),
			endpoint.NewCustomFuncEndpoint("podName", endpoint.CreatePodNameMutator()),
		)

		nsEndpoint, err := endpoint.NewNSMEndpoint(context.Background(), configuration, composite)
		if err != nil {
			logrus.Fatalf("%v", err)
		}
		if err := nsEndpoint.Start(); err != nil {
			logrus.Fatalf("Unable to start the endpoint: %v", err)
		}

		endpoints = append(endpoints, &SingleEndpoint{
			Cleanup: func() { _ = nsEndpoint.Delete() },
		})
	}
	defer func() {
		for _, e := range endpoints {
			e.Cleanup()
		}
	}()

	// Capture signals to cleanup before exiting
	<-c
}
```

## Failure Information (for bugs)

Apparently the CIDR used by the endpoint for all the services is the last one declared

```bash
$ kubectl exec -ti pgw -c sidecar -- ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
3: eth0@if6: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 1500 qdisc noqueue state UP 
    link/ether 9a:3e:df:5f:d8:9a brd ff:ff:ff:ff:ff:ff
    inet 10.244.0.5/24 brd 10.244.0.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::983e:dfff:fe5f:d89a/64 scope link 
       valid_lft forever preferred_lft forever
7: nsmExjsZmXZ: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UNKNOWN qlen 1000
    link/ether d6:66:8a:cd:b4:8e brd ff:ff:ff:ff:ff:ff
    inet 10.0.1.2/30 brd 10.0.1.3 scope global nsmExjsZmXZ
       valid_lft forever preferred_lft forever
    inet6 fe80::d466:8aff:fecd:b48e/64 scope link 
       valid_lft forever preferred_lft forever
8: nsmjHsZ0WZ: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UNKNOWN qlen 1000
    link/ether a2:eb:48:20:f6:69 brd ff:ff:ff:ff:ff:ff
    inet 10.0.1.6/30 brd 10.0.1.7 scope global nsmjHsZ0WZ
       valid_lft forever preferred_lft forever
    inet6 fe80::a0eb:48ff:fe20:f669/64 scope link 
       valid_lft forever preferred_lft forever
```

## Steps to Reproduce

1. KinD cluster creation and NSM installation
```
cat << EOF | kind create cluster --name k8s --config=-
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    image: kindest/node:v1.18.2
  - role: worker
    image: kindest/node:v1.18.2
  - role: worker
    image: kindest/node:v1.18.2
EOF
helm repo add nsm https://helm.nsm.dev/
helm repo update
helm install nsm nsm/nsm --set spire.enable=false
```

2. Compile and load NSM sidecar
```bash
docker build -t pgw:v0.1.0 --compress .
kind load docker-image pgw:v0.1.0 --name k8s
```
3. Deploy the PGW endpoint and SGW client:
```
cat <<EOF | kubectl apply -f -
apiVersion: networkservicemesh.io/v1alpha1
kind: NetworkService
metadata:
  name: lte-network
spec:
  payload: IP
  matches:
    - match:
      sourceSelector:
        link: s5u
      route:
        - destination:
          destinationSelector:
            app: pgw-u
    - match:
      sourceSelector:
        link: s5c
      route:
        - destination:
          destinationSelector:
            app: pgw-c
---
apiVersion: v1
kind: Pod
metadata:
  name: pgw
spec:
  serviceAccount: nse-acc
  containers:
    - name: sidecar
      image: pgw:v0.1.0
      env:
        - name: ADVERTISE_NSE_NAME
          value: "lte-network"
        - name: S5U_ADVERTISE_NSE_LABELS
          value: "app=pgw-u"
        - name: S5U_IP_ADDRESS
          value: "172.25.0.0/24"
        - name: S5C_ADVERTISE_NSE_LABELS
          value: "app=pgw-c"
        - name: S5C_IP_ADDRESS
          value: "172.25.1.0/24"
        - name: SGI_ADVERTISE_NSE_LABELS
          value: "app=pgw"
        - name: SGI_IP_ADDRESS
          value: "10.0.1.0/24"
      resources:
        limits:
          networkservicemesh.io/socket: 1
    - name: pgw
      image: alpine:latest
      command: ["tail", "-f", "/dev/null"]
---
apiVersion: v1
kind: Pod
metadata:
  name: sgw
  annotations:
    ns.networkservicemesh.io: lte-network/s5u3?link=s5u,lte-network/s5c4?link=s5c
spec:
  serviceAccount: nse-acc
  containers:
    - name: sgw
      image: alpine:latest
      command: ["tail", "-f", "/dev/null"]
EOF
```

## Context
```bash
$ kubectl get nodes -o wide
NAME                STATUS   ROLES    AGE   VERSION   INTERNAL-IP   EXTERNAL-IP   OS-IMAGE           KERNEL-VERSION       CONTAINER-RUNTIME
k8s-control-plane   Ready    master   51m   v1.18.2   172.80.1.4    <none>        Ubuntu 20.04 LTS   4.15.0-112-generic   containerd://1.3.3-14-g449e9269
k8s-worker          Ready    <none>   50m   v1.18.2   172.80.1.3    <none>        Ubuntu 20.04 LTS   4.15.0-112-generic   containerd://1.3.3-14-g449e9269
k8s-worker2         Ready    <none>   50m   v1.18.2   172.80.1.2    <none>        Ubuntu 20.04 LTS   4.15.0-112-generic   containerd://1.3.3-14-g449e9269
```
```
module github.com/electrocucaracha/gw-tester

go 1.15

replace github.com/census-instrumentation/opencensus-proto v0.1.0-0.20181214143942-ba49f56771b8 => github.com/census-instrumentation/opencensus-proto v0.0.3-0.20181214143942-ba49f56771b8

require (
	github.com/networkservicemesh/networkservicemesh/pkg v0.2.0
	github.com/networkservicemesh/networkservicemesh/sdk v0.2.0
	github.com/networkservicemesh/networkservicemesh/utils v0.2.0
	github.com/sirupsen/logrus v1.6.0
)
```
## Failure Logs

These are the logs collected from the sidecar for the **s5u** labeled network:
```
time="2020-09-11T15:58:54Z" level=info msg="==--> Endpoint.Request() span:3c03f1dcead3c4d7:7e781c275baef2c2:348817d3d78bdcc0:1"
time="2020-09-11T15:58:54Z" level=info msg=">><<-- request={\"connection\":{\"id\":\"2\",\"network_service\":\"lte-network\",\"context\":{\"ip_context\":{\"src_ip_required\":true,\"dst_ip_required\":true,\"excluded_prefixes\":[\"10.244.0.0/16\",\"10.96.0.0/12\",\"10.244.0.0/16\",\"10.96.0.0/12\"]}},\"labels\":{\"l
ink\":\"s5u\",\"namespace\":\"default\",\"podName\":\"sgw\"},\"network_service_managers\":[\"k8s-control-plane\"]},\"mechanism_preferences\":[{\"type\":\"MEMIF\"},{\"type\":\"KERNEL_INTERFACE\"}]} span=3c03f1dcead3c4d7:7e781c275baef2c2:348817d3d78bdcc0:1"
time="2020-09-11T15:58:54Z" level=info msg="Request for Network Service received connection:<id:\"2\" network_service:\"lte-network\" context:<ip_context:<src_ip_required:true dst_ip_required:true excluded_prefixes:\"10.244.0.0/16\" excluded_prefixes:\"10.96.0.0/12\" excluded_prefixes:\"10.244.0.0/16\" excluded_pr
efixes:\"10.96.0.0/12\" > > labels:<key:\"link\" value:\"s5u\" > labels:<key:\"namespace\" value:\"default\" > labels:<key:\"podName\" value:\"sgw\" > network_service_managers:\"k8s-control-plane\" > mechanism_preferences:<type:\"MEMIF\" > mechanism_preferences:<type:\"KERNEL_INTERFACE\" > " operation=Endpoint.Req
uest span="3c03f1dcead3c4d7:7e781c275baef2c2:348817d3d78bdcc0:1"
time="2020-09-11T15:58:54Z" level=info msg="==--> *MonitorEndpoint.Request() span:3c03f1dcead3c4d7:67bfeea8e82b2bc4:348817d3d78bdcc0:1"
time="2020-09-11T15:58:54Z" level=info msg=">><<-- request={\"connection\":{\"id\":\"2\",\"network_service\":\"lte-network\",\"context\":{\"ip_context\":{\"src_ip_required\":true,\"dst_ip_required\":true,\"excluded_prefixes\":[\"10.244.0.0/16\",\"10.96.0.0/12\",\"10.244.0.0/16\",\"10.96.0.0/12\"]}},\"labels\":{\"l
ink\":\"s5u\",\"namespace\":\"default\",\"podName\":\"sgw\"},\"network_service_managers\":[\"k8s-control-plane\"]},\"mechanism_preferences\":[{\"type\":\"MEMIF\"},{\"type\":\"KERNEL_INTERFACE\"}]} span=3c03f1dcead3c4d7:67bfeea8e82b2bc4:348817d3d78bdcc0:1"
time="2020-09-11T15:58:54Z" level=info msg="==----> *ConnectionEndpoint.Request() span:3c03f1dcead3c4d7:2b3fb9dcf85c23d5:67bfeea8e82b2bc4:1"
time="2020-09-11T15:58:54Z" level=info msg=">><<---- request={\"connection\":{\"id\":\"2\",\"network_service\":\"lte-network\",\"context\":{\"ip_context\":{\"src_ip_required\":true,\"dst_ip_required\":true,\"excluded_prefixes\":[\"10.244.0.0/16\",\"10.96.0.0/12\",\"10.244.0.0/16\",\"10.96.0.0/12\"]}},\"labels\":{\
"link\":\"s5u\",\"namespace\":\"default\",\"podName\":\"sgw\"},\"network_service_managers\":[\"k8s-control-plane\"]},\"mechanism_preferences\":[{\"type\":\"MEMIF\"},{\"type\":\"KERNEL_INTERFACE\"}]} span=3c03f1dcead3c4d7:2b3fb9dcf85c23d5:67bfeea8e82b2bc4:1"
time="2020-09-11T15:58:54Z" level=info msg="==------> *IpamEndpoint.Request() span:3c03f1dcead3c4d7:2dc88667806dccfb:2b3fb9dcf85c23d5:1"
time="2020-09-11T15:58:54Z" level=info msg=">><<------ request={\"connection\":{\"id\":\"2\",\"network_service\":\"lte-network\",\"mechanism\":{\"cls\":\"LOCAL\",\"type\":\"KERNEL_INTERFACE\",\"parameters\":{\"description\":\"NSM Endpoint\",\"name\":\"nsmExjsZmXZ\",\"netnsInode\":\"4026533091\",\"socketfile\":\"ns
mExjsZmXZ/memif.sock\"}},\"context\":{\"ip_context\":{\"src_ip_required\":true,\"dst_ip_required\":true,\"excluded_prefixes\":[\"10.244.0.0/16\",\"10.96.0.0/12\",\"10.244.0.0/16\",\"10.96.0.0/12\"]}},\"labels\":{\"link\":\"s5u\",\"namespace\":\"default\",\"podName\":\"sgw\"},\"network_service_managers\":[\"k8s-con
trol-plane\"]},\"mechanism_preferences\":[{\"type\":\"MEMIF\"},{\"type\":\"KERNEL_INTERFACE\"}]} span=3c03f1dcead3c4d7:2dc88667806dccfb:2b3fb9dcf85c23d5:1"
time="2020-09-11T15:58:54Z" level=info msg="==--------> *CustomFuncEndpoint.Request() span:3c03f1dcead3c4d7:1cbd10d3f1f1ac52:2dc88667806dccfb:1"
time="2020-09-11T15:58:54Z" level=info msg=">><<-------- request={\"connection\":{\"id\":\"2\",\"network_service\":\"lte-network\",\"mechanism\":{\"cls\":\"LOCAL\",\"type\":\"KERNEL_INTERFACE\",\"parameters\":{\"description\":\"NSM Endpoint\",\"name\":\"nsmExjsZmXZ\",\"netnsInode\":\"4026533091\",\"socketfile\":\"
nsmExjsZmXZ/memif.sock\"}},\"context\":{\"ip_context\":{\"src_ip_addr\":\"10.0.1.1/30\",\"dst_ip_addr\":\"10.0.1.2/30\",\"src_ip_required\":true,\"dst_ip_required\":true,\"excluded_prefixes\":[\"10.244.0.0/16\",\"10.96.0.0/12\",\"10.244.0.0/16\",\"10.96.0.0/12\"]}},\"labels\":{\"link\":\"s5u\",\"namespace\":\"defa
ult\",\"podName\":\"sgw\"},\"network_service_managers\":[\"k8s-control-plane\"]},\"mechanism_preferences\":[{\"type\":\"MEMIF\"},{\"type\":\"KERNEL_INTERFACE\"}]} span=3c03f1dcead3c4d7:1cbd10d3f1f1ac52:2dc88667806dccfb:1"
time="2020-09-11T15:58:54Z" level=info msg="NSM_NAMESPACE not found."
time="2020-09-11T15:58:54Z" level=info msg="podName endpoint completed on connection: id:\"2\" network_service:\"lte-network\" mechanism:<cls:\"LOCAL\" type:\"KERNEL_INTERFACE\" parameters:<key:\"description\" value:\"NSM Endpoint\" > parameters:<key:\"name\" value:\"nsmExjsZmXZ\" > parameters:<key:\"netnsInode\" 
value:\"4026533091\" > parameters:<key:\"socketfile\" value:\"nsmExjsZmXZ/memif.sock\" > > context:<ip_context:<src_ip_addr:\"10.0.1.1/30\" dst_ip_addr:\"10.0.1.2/30\" src_ip_required:true dst_ip_required:true excluded_prefixes:\"10.244.0.0/16\" excluded_prefixes:\"10.96.0.0/12\" excluded_prefixes:\"10.244.0.0/16\
" excluded_prefixes:\"10.96.0.0/12\" > > labels:<key:\"link\" value:\"s5u\" > labels:<key:\"namespace\" value:\"default\" > labels:<key:\"podName\" value:\"pgw\" > network_service_managers:\"k8s-control-plane\" " operation="*CustomFuncEndpoint.Request" span="3c03f1dcead3c4d7:1cbd10d3f1f1ac52:2dc88667806dccfb:1"
time="2020-09-11T15:58:54Z" level=info msg=">><<-------- response={\"id\":\"2\",\"network_service\":\"lte-network\",\"mechanism\":{\"cls\":\"LOCAL\",\"type\":\"KERNEL_INTERFACE\",\"parameters\":{\"description\":\"NSM Endpoint\",\"name\":\"nsmExjsZmXZ\",\"netnsInode\":\"4026533091\",\"socketfile\":\"nsmExjsZmXZ/mem
if.sock\"}},\"context\":{\"ip_context\":{\"src_ip_addr\":\"10.0.1.1/30\",\"dst_ip_addr\":\"10.0.1.2/30\",\"src_ip_required\":true,\"dst_ip_required\":true,\"excluded_prefixes\":[\"10.244.0.0/16\",\"10.96.0.0/12\",\"10.244.0.0/16\",\"10.96.0.0/12\"]}},\"labels\":{\"link\":\"s5u\",\"namespace\":\"default\",\"podName
\":\"pgw\"},\"network_service_managers\":[\"k8s-control-plane\"]} span=3c03f1dcead3c4d7:1cbd10d3f1f1ac52:2dc88667806dccfb:1"
```
These are the logs collected from the sidecar for the **s5c** labeled network:
```
time="2020-09-11T15:58:54Z" level=info msg="==--> Endpoint.Request() span:3c03f1dcead3c4d7:15c8c043df189f43:4ef6918ec37444b0:1"
time="2020-09-11T15:58:54Z" level=info msg=">><<-- request={\"connection\":{\"id\":\"4\",\"network_service\":\"lte-network\",\"context\":{\"ip_context\":{\"src_ip_required\":true,\"dst_ip_required\":true,\"excluded_prefixes\":[\"10.244.0.0/16\",\"10.96.0.0/12\",\"10.244.0.0/16\",\"10.96.0.0/12\"]}},\"labels\":{\"l
ink\":\"s5c\",\"namespace\":\"default\",\"podName\":\"sgw\"},\"network_service_managers\":[\"k8s-control-plane\"]},\"mechanism_preferences\":[{\"type\":\"MEMIF\"},{\"type\":\"KERNEL_INTERFACE\"}]} span=3c03f1dcead3c4d7:15c8c043df189f43:4ef6918ec37444b0:1"                                                            time="2020-09-11T15:58:54Z" level=info msg="Request for Network Service received connection:<id:\"4\" network_service:\"lte-network\" context:<ip_context:<src_ip_required:true dst_ip_required:true excluded_prefixes:\"10.244.0.0/16\" excluded_prefixes:\"10.96.0.0/12\" excluded_prefixes:\"10.244.0.0/16\" excluded_prefixes:\"10.96.0.0/12\" > > labels:<key:\"link\" value:\"s5c\" > labels:<key:\"namespace\" value:\"default\" > labels:<key:\"podName\" value:\"sgw\" > network_service_managers:\"k8s-control-plane\" > mechanism_preferences:<type:\"MEMIF\" > mechanism_preferences:<type:\"KERNEL_INTERFACE\" > " operation=Endpoint.Req
uest span="3c03f1dcead3c4d7:15c8c043df189f43:4ef6918ec37444b0:1"                                                                                             
time="2020-09-11T15:58:54Z" level=info msg="==--> *MonitorEndpoint.Request() span:3c03f1dcead3c4d7:4898bd00414997d9:4ef6918ec37444b0:1"                                                                                                                                                                                    
time="2020-09-11T15:58:54Z" level=info msg=">><<-- request={\"connection\":{\"id\":\"4\",\"network_service\":\"lte-network\",\"context\":{\"ip_context\":{\"src_ip_required\":true,\"dst_ip_required\":true,\"excluded_prefixes\":[\"10.244.0.0/16\",\"10.96.0.0/12\",\"10.244.0.0/16\",\"10.96.0.0/12\"]}},\"labels\":{\"l
ink\":\"s5c\",\"namespace\":\"default\",\"podName\":\"sgw\"},\"network_service_managers\":[\"k8s-control-plane\"]},\"mechanism_preferences\":[{\"type\":\"MEMIF\"},{\"type\":\"KERNEL_INTERFACE\"}]} span=3c03f1dcead3c4d7:4898bd00414997d9:4ef6918ec37444b0:1"
time="2020-09-11T15:58:54Z" level=info msg="==----> *ConnectionEndpoint.Request() span:3c03f1dcead3c4d7:22771117e7fc0234:4898bd00414997d9:1"
time="2020-09-11T15:58:54Z" level=info msg=">><<---- request={\"connection\":{\"id\":\"4\",\"network_service\":\"lte-network\",\"context\":{\"ip_context\":{\"src_ip_required\":true,\"dst_ip_required\":true,\"excluded_prefixes\":[\"10.244.0.0/16\",\"10.96.0.0/12\",\"10.244.0.0/16\",\"10.96.0.0/12\"]}},\"labels\":{\
"link\":\"s5c\",\"namespace\":\"default\",\"podName\":\"sgw\"},\"network_service_managers\":[\"k8s-control-plane\"]},\"mechanism_preferences\":[{\"type\":\"MEMIF\"},{\"type\":\"KERNEL_INTERFACE\"}]} span=3c03f1dcead3c4d7:22771117e7fc0234:4898bd00414997d9:1"
time="2020-09-11T15:58:54Z" level=info msg="==------> *IpamEndpoint.Request() span:3c03f1dcead3c4d7:444ff6fafc998f44:22771117e7fc0234:1"
time="2020-09-11T15:58:54Z" level=info msg=">><<------ request={\"connection\":{\"id\":\"4\",\"network_service\":\"lte-network\",\"mechanism\":{\"cls\":\"LOCAL\",\"type\":\"KERNEL_INTERFACE\",\"parameters\":{\"description\":\"NSM Endpoint\",\"name\":\"nsmjHsZ0WZ\",\"netnsInode\":\"4026533091\",\"socketfile\":\"nsm
jHsZ0WZ/memif.sock\"}},\"context\":{\"ip_context\":{\"src_ip_required\":true,\"dst_ip_required\":true,\"excluded_prefixes\":[\"10.244.0.0/16\",\"10.96.0.0/12\",\"10.244.0.0/16\",\"10.96.0.0/12\"]}},\"labels\":{\"link\":\"s5c\",\"namespace\":\"default\",\"podName\":\"sgw\"},\"network_service_managers\":[\"k8s-contr
ol-plane\"]},\"mechanism_preferences\":[{\"type\":\"MEMIF\"},{\"type\":\"KERNEL_INTERFACE\"}]} span=3c03f1dcead3c4d7:444ff6fafc998f44:22771117e7fc0234:1"
time="2020-09-11T15:58:54Z" level=info msg="==--------> *CustomFuncEndpoint.Request() span:3c03f1dcead3c4d7:19d0071aaed97981:444ff6fafc998f44:1"
time="2020-09-11T15:58:54Z" level=info msg=">><<-------- request={\"connection\":{\"id\":\"4\",\"network_service\":\"lte-network\",\"mechanism\":{\"cls\":\"LOCAL\",\"type\":\"KERNEL_INTERFACE\",\"parameters\":{\"description\":\"NSM Endpoint\",\"name\":\"nsmjHsZ0WZ\",\"netnsInode\":\"4026533091\",\"socketfile\":\"n
smjHsZ0WZ/memif.sock\"}},\"context\":{\"ip_context\":{\"src_ip_addr\":\"10.0.1.5/30\",\"dst_ip_addr\":\"10.0.1.6/30\",\"src_ip_required\":true,\"dst_ip_required\":true,\"excluded_prefixes\":[\"10.244.0.0/16\",\"10.96.0.0/12\",\"10.244.0.0/16\",\"10.96.0.0/12\"]}},\"labels\":{\"link\":\"s5c\",\"namespace\":\"defaul
t\",\"podName\":\"sgw\"},\"network_service_managers\":[\"k8s-control-plane\"]},\"mechanism_preferences\":[{\"type\":\"MEMIF\"},{\"type\":\"KERNEL_INTERFACE\"}]} span=3c03f1dcead3c4d7:19d0071aaed97981:444ff6fafc998f44:1"
time="2020-09-11T15:58:54Z" level=info msg="NSM_NAMESPACE not found."
time="2020-09-11T15:58:54Z" level=info msg="podName endpoint completed on connection: id:\"4\" network_service:\"lte-network\" mechanism:<cls:\"LOCAL\" type:\"KERNEL_INTERFACE\" parameters:<key:\"description\" value:\"NSM Endpoint\" > parameters:<key:\"name\" value:\"nsmjHsZ0WZ\" > parameters:<key:\"netnsInode\" v
alue:\"4026533091\" > parameters:<key:\"socketfile\" value:\"nsmjHsZ0WZ/memif.sock\" > > context:<ip_context:<src_ip_addr:\"10.0.1.5/30\" dst_ip_addr:\"10.0.1.6/30\" src_ip_required:true dst_ip_required:true excluded_prefixes:\"10.244.0.0/16\" excluded_prefixes:\"10.96.0.0/12\" excluded_prefixes:\"10.244.0.0/16\" 
excluded_prefixes:\"10.96.0.0/12\" > > labels:<key:\"link\" value:\"s5c\" > labels:<key:\"namespace\" value:\"default\" > labels:<key:\"podName\" value:\"pgw\" > network_service_managers:\"k8s-control-plane\" " operation="*CustomFuncEndpoint.Request" span="3c03f1dcead3c4d7:19d0071aaed97981:444ff6fafc998f44:1"
time="2020-09-11T15:58:54Z" level=info msg=">><<-------- response={\"id\":\"4\",\"network_service\":\"lte-network\",\"mechanism\":{\"cls\":\"LOCAL\",\"type\":\"KERNEL_INTERFACE\",\"parameters\":{\"description\":\"NSM Endpoint\",\"name\":\"nsmjHsZ0WZ\",\"netnsInode\":\"4026533091\",\"socketfile\":\"nsmjHsZ0WZ/memif
.sock\"}},\"context\":{\"ip_context\":{\"src_ip_addr\":\"10.0.1.5/30\",\"dst_ip_addr\":\"10.0.1.6/30\",\"src_ip_required\":true,\"dst_ip_required\":true,\"excluded_prefixes\":[\"10.244.0.0/16\",\"10.96.0.0/12\",\"10.244.0.0/16\",\"10.96.0.0/12\"]}},\"labels\":{\"link\":\"s5c\",\"namespace\":\"default\",\"podName\"
:\"pgw\"},\"network_service_managers\":[\"k8s-control-plane\"]} span=3c03f1dcead3c4d7:19d0071aaed97981:444ff6fafc998f44:1"
```

**Comment by edwarnicke** [comment]
Let's definitely see if we can fix this 👍

**Comment by xzfc** [comment]
Hello.

You've stumbled into a limitation of the current version of SDK, which doesn't provide a way to register multiple NSEs per single `NsmEndpoint` instance nor handles well multiple `NsmEndpoint` instances at the same time. Specifically, under the hood of your code example, each new `NsmEndpoint` overwrites the client socket created by the previous one, so the last one takes precedence.

Currently, I am working on providing an additional API in SDK to register multiple NSE per single client socket and switch over them.

**Comment by electrocucaracha** [comment]
Hi @xzfc, Thanks for explaining this SDK limitation and highlighting the overwrite on client sockets. My workaround for this was to create multiple sidecars in the same pod.
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: pgw
spec:
  serviceAccount: nse-acc
  containers:
    - name: sidecar-sgi
      image: nse:v0.2.0
      env:
        - name: ADVERTISE_NSE_NAME
          value: "lte-network"
        - name: ADVERTISE_NSE_LABELS
          value: "app=http-server-sgi"
        - name: IP_ADDRESS
          value: "10.0.1.0/24"
        - name: ROUTE
          value: "10.0.3.0/24"
      resources:
        limits:
          networkservicemesh.io/socket: 1
    - name: sidecar-s5u
      image: nse:v0.2.0
      env:
        - name: ADVERTISE_NSE_NAME
          value: "lte-network"
        - name: ADVERTISE_NSE_LABELS
          value: "app=pgw-s5u"
        - name: IP_ADDRESS
          value: "172.25.0.0/24"
      resources:
        limits:
          networkservicemesh.io/socket: 1
    - name: sidecar-s5c
      image: nse:v0.2.0
      env:
        - name: ADVERTISE_NSE_NAME
          value: "lte-network"
        - name: ADVERTISE_NSE_LABELS
          value: "app=pgw-s5c"
        - name: IP_ADDRESS
          value: "172.25.1.0/24"
      resources:
        limits:
          networkservicemesh.io/socket: 1
    - name: pgw
      image: alpine:latest
      command: ["tail", "-f", "/dev/null"]
```
More likely it's not the cleanest solution but at least it works. I have the End-to-End deployment instructions [here](https://github.com/electrocucaracha/gw-tester). I'll keep an eye on future NSM changes.
