### ISSUE TITLE
Extending Network Service API further to support network service and source label rewrite

### ISSUE THREAD

**Issue by edwarnicke** [networkservicemesh/networkservicemesh#532]
See #531 for initial explanation of the API to be extended here.

```yaml
  - match:
    sourceSelector:
      app: firewall
      alternate: foo
    rewrite:
      networkService: alternate-secure-intranet-connectivity
      sourceLabels:
        alternate: ""
        app: foo
```
Would add to the 'match' object an 'action' that is not 'route', but rather 'rewrite'.  The 'rewrite' action could rewrite the networkService to be connected to, delete labels (by setting them to "") or add/alter labels by specifying them.
