### ISSUE TITLE
Publish the cross-connect status as CRD.

### ISSUE THREAD

**Issue by nickolaev** [networkservicemesh/networkservicemesh#831]
## Overview

NSM defines a nice monitoring gRPC interface [described as protobuf](https://github.com/networkservicemesh/networkservicemesh/blob/master/controlplane/pkg/apis/crossconnect/crossconnect.proto). It is used in the [`crossconnect-monitor`](https://github.com/networkservicemesh/networkservicemesh/blob/master/k8s/cmd/crossconnect-monitor/crossconnect_monitor.go#L38) to subscribe to the event stream and print the received events. It is also used by out `skydive` agent to collect the information for visualisation.

The proposal in this issue is to extend crossconenct-monitor to also publish these events in a dedicated Kubernetes CRD. This can be useful for e.g. monitoring systems registering the updates and having visibility into the Network Service Mesh and Endpoint status.

A suggested CRD definition:

```yaml
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: networkserviceconnections.networkservicemesh.io
spec:
  conversion:
    strategy: None
  group: networkservicemesh.io
  names:
    kind: NetworkServiceConnection
    listKind: NetworkServiceConnectionList
    plural: networkserviceconnections
    shortNames:
      - nsconn
      - nsconns
    singular: networkserviceconnection
  scope: Cluster
  version: v1
  versions:
    - name: v1
      served: true
      storage: true
```
