### ISSUE TITLE
Implement spf13/viper configuration in the SDK

### ISSUE THREAD

**Issue by nickolaev** [networkservicemesh/networkservicemesh#866]
## Overview

A continuation of the discussion started in #832.

The proposal is to reconsider the way we configure Clients and Endpoints in the SDK. We propose 3 changes:
 * migrate to using `spf13/viper` as the configuration management engine
 * rename ENV variables
 * [optional] enable ConfigMap based configuration

## References

#832

**Comment by nickolaev** [comment]
@matrohon @edwarnicke  ideas welcome.

**Comment by matrohon** [comment]
concerning the ENV variables used by the sdk, I would suggest a simpler approach with the following names : 

- NETWORK_SERVICE : replace OutgoingNscName and AdvertiseNseName
- LABELS : replace OutgoingNscLabels and AdvertiseNseLabels

Then those ENV would be used during the endpoint advertisement or during the client startup depending on the goal of the application (implementing a nsm endpoint or being a nsm client).

**Comment by nickolaev** [comment]
@matrohon all the env variables are [here]( https://github.com/networkservicemesh/networkservicemesh/blob/master/sdk/common/configuration.go#L25):
```go
const (
	advertiseNseNameEnv   = "ADVERTISE_NSE_NAME"
	advertiseNseLabelsEnv = "ADVERTISE_NSE_LABELS"
	outgoingNscNameEnv    = "OUTGOING_NSC_NAME"
	outgoingNscLabelsEnv  = "OUTGOING_NSC_LABELS"
	tracerEnabled         = "TRACER_ENABLED"
	mechanismTypeEnv      = "MECHANISM_TYPE"
	ipAddressEnv          = "IP_ADDRESS"
)
```

The tricky part is that the Endpoint can be [both](https://github.com/networkservicemesh/networkservicemesh/blob/master/k8s/conf/vppagent-firewall-nse.yaml#L20):
```yaml
        - name: firewall-nse
          image: networkservicemesh/vppagent-firewall-nse:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: ADVERTISE_NSE_NAME
              value: "secure-intranet-connectivity"
            - name: ADVERTISE_NSE_LABELS
              value: "app=firewall"
            - name: OUTGOING_NSC_NAME
              value: "secure-intranet-connectivity"
            - name: OUTGOING_NSC_LABELS
              value: "app=firewall"
            - name: TRACER_ENABLED
              value: "true"
```

In this case the `vppagent-firewall` is implementing `secure-intranet-connectivity` and labelling its Endpoint registration with `app: firewall`. When the connection request is received, it will initiate a connection to `secure-intranet-connectivity`, labelling its own connection request with `app: firewall`.
The fact that both the adveritsed NS/label and the requested NS/label are the same is more or less accidental. We can very well request another NS and label the request with something else. Such an example would look like this:

```yaml
        - name: firewall-nse
          image: networkservicemesh/vppagent-firewall-nse:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: ADVERTISE_NSE_NAME
              value: "secure-intranet-connectivity"
            - name: ADVERTISE_NSE_LABELS
              value: "app=firewall"
            - name: OUTGOING_NSC_NAME
              value: "secure-gateway"
            - name: OUTGOING_NSC_LABELS
              value: "app=firewall,gw=v2"
            - name: TRACER_ENABLED
              value: "true"
```

Saying this, my proposal for naming will be:
 * `ENDPOINT_NETWORK_SERVICE`
 * `ENDPOINT_LABELS`
 * `CLIENT_NETWORK_SERVICE`
 * `CLIENT_LABELS`

Note that I am trying to avoid the NSE/NSC terminology and using Endpoint/Client as it sounds more explicit (and clearer when pronouncing).
