### ISSUE TITLE
Investigate sidecar approach for NSM

### ISSUE THREAD

**Issue by mestery** [networkservicemesh/networkservicemesh#98]
Similar to Istio, we may want to use a sidecar model where we put a container into each pod which is run.

**Comment by prateekgogia** [comment]
I added some details in the wiki https://github.com/ligato/networkservicemesh/wiki/Adding-sidecar-containers, would love to get some feedback.

**Comment by edwarnicke** [comment]
@prateekgogia is this what you mean by MutatingWebhookConfiguration https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/

**Comment by prateekgogia** [comment]
@edwarnicke Yes! This is the example on the link you copied, which refers to MutatingWebhookConfiguration 
```
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: <name of this configuration object>
webhooks:
- name: <webhook name, e.g., pod-policy.example.io>
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - pods
  clientConfig:
    service:
      namespace: <namespace of the front-end service>
      name: <name of the front-end service>
    caBundle: <pem encoded ca cert that signs the server cert used by the webhook> 
```
